In [64]:
import numpy as np

list1 =[11,22,33]
a=np.array(list1)
print(a)

[11 22 33]


In [15]:
import numpy as np

arr =np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [25]:
import numpy as np

a=np.array([42])#0
b=np.array([1, 2, 3, 4, 5])#1d
c=np.array([[1,2,3],[4,5,6]])#2d
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3]]])#3d

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

1
1
2
1


C:\Users\acer\AppData\Local\Temp\ipykernel_20256\2311633316.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[[1,2,3],[4,5,6]],[[1,2,3]]])#3d


In [32]:
arr =np.array([1,2,3,4])
print(arr[0])

1


In [33]:
arr =np.array([1,2,3,4])
print(arr[1]+arr[2])

5


In [35]:
arr =np.array([1,2,3,4])
print(arr[1]*arr[2])

6


In [38]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:', arr[0,1])

2nd element on 1st row: 2


In [41]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row:', arr[0]+arr[1])

2nd element on 1st row: [ 7  9 11 13 15]


In [43]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,1,2])

6


In [45]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim:' , arr[1,-1])

last element from 2nd dim: 10


In [59]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1]+arr[0])


[[ 8 10 12]
 [14 16 18]]


In [63]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2] + arr[0,0,2] + arr[1,0,2] + arr[1,1,2])

30
